config/routes.rb
Bookmeetups::Application.routes.draw do
  root to: 'users#landing'

  post "/search", to: "searches#search"
  get "users/landing", to: "users#landing"
  resources :users, :except => [:index] do
    post 'books/:book_id', to: 'favorite_books#create', as: 'create_favorite_book'
    delete 'books/:book_id', to: 'favorite_books#destroy', as: 'favorite_book'
    get 'books', to: 'favorite_books#index', as: 'favorite_books'
    get 'books/:book_id/new_meetup', to: 'meetups#create', as: 'create_meetup'
    resources :meetups, :except => [:new, :edit, :create, :destroy]
    resources :photos, :only => [:show, :new, :create, :destroy] do
      get "serve", :on => :member
    end
  end

  resources :books, only: [:show, :index]
  resources :sessions, :only => [:new, :create, :destroy]

  resources :meetups, :only => [] do
    resources :messages, only: [:new, :create]
  end


  get "/search/:s", to: "searches#results"
  get "/search", to: "searches#results"
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :user_meetups
  has_many :users, through: :user_meetups
  has_many :messages
  belongs_to :book

  def unread_messages(u_id)
    num = 0
    messages.each do |message|
      num += 1   if message.user_id != u_id && message.unread
    end
    num
  end

  def mark_read(user)
    messages.each do |message|
      unless message.user_id == user.id
        if message.unread
          message.unread = false
          message.save
          user.unread -= 1
          user.save
        end
      end
    end
  end

  def other_user(user)
    (users - [user]).first
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_filter :redirect_unless_logged_in
  before_filter :redirect_unless_authorized, :only => [:index]

  def index
    @meetups = current_user.meetups.uniq
    render :index
  end

  def create
    @other_user = User.find(params[:user_id])
    book = Book.find(params[:book_id])
    book.meetups.each do |existing_meetup|
      @meetup = existing_meetup if (existing_meetup.users.include?(current_user ) &&
                                    existing_meetup.users.include?(User.find(params[:user_id])))
    end
    unless @meetup
      @meetup = Meetup.create
      book.meetups << @meetup
      current_user.meetups << @meetup
      @other_user.meetups << @meetup
    end
    @messages = @meetup.messages.order("created_at DESC")
    render  :"show"
  end

  def show
    @meetup = Meetup.where(id: params[:id]).first
    if current_user.id == params[:user_id].to_i
      @other_user = (@meetup.users - [current_user]).first
      @messages = @meetup.messages.order("created_at DESC")
      @meetup.mark_read(current_user)
      render :show
    else
      redirect_to user_favorite_books_path(session[:id])
    end
  end
end

app/views/meetups/_index.html.erb
<h1>Meetups!</h1>

<% @meetups.each do |meetup| %>
  <p><%= meetup.book.title %></p>
  <%= link_to 'hello', user_meetup_path(current_user, meetup) %>
  participants:
  <% meetup.users.each do |user| %>
  <li><%= user.username %></li>
  <% end %>
<% end %>

app/views/meetups/index.html.erb
<!-- <h1>Meetups!</h1> -->
<% @meetups.each do |meetup| %>

  <div class="book_pic">
    <%= link_to image_tag(meetup.book.photo_link(1)), book_path(meetup.book) %>
  </div>
  <div class="info">
    <div class="unread">
      <p><%= "You have #{meetup.unread_messages(current_user.id)} new messages!" if meetup.unread_messages(current_user.id) != 0%></p>
    </div>

    <% meetup.users.each do |user| %>
      <% if user != current_user %>
        <h3>Meetup with <span class="meetup_user"><%= link_to user.username.capitalize, user_path(user) %></span></h3>
        <h4><%= user.location.city %></h4>
      <% end %>
    <% end %>
    <%= link_to 'Go to Messages', user_meetup_path(current_user, meetup) %>
  </div>

<% end %>

app/views/meetups/show.html.erb
<div class="meetup-messages" id="<%= @meetup.id %>">
    <% if @meetup.users.include? current_user%>
      <h2><%= link_to @meetup.book.title, book_path(@meetup.book) %> meetup with <%= link_to @other_user.username, user_path(@other_user) %></h2>
       <%= link_to 'Compose new message', new_meetup_message_path(@meetup), :class => 'open-new-message', remote: true %>
    <div class="messages">
      <% if @messages %>
        <% @messages.each do |message| %>
          <%= render partial: "messages/created_message", locals: { message: message} %>
        <% end %>
      <% end %>
    <% else %>
      <h1>Uhhhh...get out of here. You don't have permission</h1>
    <% end %>
    <footer></footer>
  </div>
</div>