config/routes.rb
Bookmeetups::Application.routes.draw do
  root to: 'users#landing'

  post "/search", to: "searches#search"
  get "users/landing", to: "users#landing"
  resources :users, :except => [:index] do
    post 'books/:book_id', to: 'favorite_books#create', as: 'create_favorite_book'
    delete 'books/:book_id', to: 'favorite_books#destroy', as: 'favorite_book'
    get 'books', to: 'favorite_books#index', as: 'favorite_books'
    get 'books/:book_id/new_meetup', to: 'meetups#create', as: 'create_meetup'
    resources :meetups, :except => [:new, :edit, :create, :destroy]
    resources :photos, :only => [:show, :new, :create, :destroy] do
      get "serve", :on => :member
    end
  end

  resources :books, only: [:show, :index]
  resources :sessions, :only => [:new, :create, :destroy]

  resources :meetups, :only => [] do
    resources :messages, only: [:new, :create]
  end


  get "/search/:s", to: "searches#results"
  get "/search", to: "searches#results"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :username, :password_digest, :email, :location_id
  validates_uniqueness_of :username, :email, case_sensitive: false

  has_one :photo
  has_many :favorite_books
  has_many :books, through: :favorite_books
  has_many :user_meetups
  has_many :meetups, through: :user_meetups
  belongs_to :location
  has_many :messages

  def new_unread_message
    self.unread += 1
    self.save
  end

  def friends(book)
    location.locations_within_range( travel_distance ).each_with_object([]) do |locale, coll|
      coll << friends_at_location( locale, [book] )
    end.flatten
  end

  def book_friends
    b= self.books.to_a
    location.locations_within_range( travel_distance ).each_with_object([]) do |locale, coll |
      coll << friends_at_location( locale, b )
    end.flatten
  end

  def friends_at_location( location, books )
    location.users.includes(:books).select do |user|
      user if user != self &&
      user.books.any?{ |users_book| books.include?( users_book ) }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :redirect_unless_logged_in, :except => [:new, :create, :landing]
  before_filter :redirect_unless_authorized, :only => [:edit, :update, :destroy]
  before_filter :redirect_unless_form_filled, :only => [:update, :create]
  before_filter :redirect_without_valid_zip, :only => [:update, :create]

  def new
    if logged_in?
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    new_user = UserBuilder.new(params[:user]).build
    location = LocationBuilder.new(params[:zip]).build
    location.users << new_user
    if new_user.save
      session[:id] = new_user.id
      redirect_to(user_path(new_user))
    else
      redirect_to(new_user_path, :flash => {:error => "Invalid sign up"})
    end
  end

  def show
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_favorite_books_path(@user)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    location = LocationBuilder.new(params[:user][:zip]).build
    @user.travel_distance =  params[:user][:travel_distance]
    @user.save
    @user.update_attribute(:location, location)
    redirect_to(user_path(@user))
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session.clear
    redirect_to(root_path)
  end

  def landing
    if logged_in?
      redirect_to(user_path(session[:id]))
    else
      render :landing
    end
  end

end

app/views/users/books_index.html.erb
<div class="profile_pic">
  <%= render partial: "photos/show", locals: { user: @user } %>
</div>
<div class="info">
  <h3><%= @user.username.titlecase %></h3>
   <h4><%= !@user.location.nil? ? "#{@user.location.city}, #{@user.location.state}" : "No location set." %></h4>
  <% if @user == current_user %>
    <%= link_to "Edit My Profile", edit_user_path(current_user) %>
  <% end %>
</div>

<% if current_user != @user %>
    <div class="book_list">
    <p>Books in Common with <%= @user.username.titlecase %>:</p>
      <% books_in_common_with(@user).each do |book| %>
        <div class="book-display">
          <div class="title"><%= book.title %></div>
          <%= link_to image_tag(book.photo_link(1)), book_path(book), :class => 'cover' %>
            <%= link_to "Meet Up!", user_create_meetup_path(@user, book), class: "meetup" %>
        </div>
      <% end %>
    </div>

    <div class="book_list">
    <p><%= @user.username.titlecase %>'s Books:</p>
      <% other_books_of(@user).each do |book| %>
        <div class="book-display">
          <div class="title"><%= book.title %></div>
          <%= link_to image_tag(book.photo_link(1)), book_path(book), :class => 'cover' %>
        </div>
      <% end %>
    </div>

<% else %>
  <div class="book_list">
    <% @user.books.each do |book| %>
      <div class="book-display">
        <div class="title">
          <%= book.title %>
        </div>
        <%= link_to image_tag(book.photo_link(1)), book_path(book), :class => 'cover' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="edit_user">
  <header><h1>Edit User info</h1></header>
  <%= form_for :user, :url => user_path, :method => :put do |user| %>
        <h3>Zip</h3>
        <%= user.text_field(:zip, :size => "15", :required => true, :pattern => '^\d{5}$', :value => current_user.location.blank? ? "Zip code" : current_user.location.zip) %>
        <h3>Will Travel
        <%= user.text_field(:travel_distance, :size => "10", :required => true, :pattern => '^\d+', :value => current_user.travel_distance.blank? ?
        "Miles" : current_user.travel_distance) %> Miles To Meet New Friends!</h3>
        <%= user.submit "Update Location", class: "update" %>
        <%= link_to "Add New Profile Pic", new_user_photo_path(@user), class: "add" %>
  <% end %>
</div>

app/views/users/landing.html.erb
<div class="landing">
  <h1>Your <span class="strong">best</span> friends are your <span class="strong">book</span> friends.</h1>
  <%= link_to "Sign In", new_session_path, :class => "hero-btn" %>
  <%= link_to "Sign Up", new_user_path, :class => "hero-btn"%>
</div>

app/views/users/new.html.erb
<div class='splash'>
  <h1>Welcome!</h1>
  <%= form_for @user do |f| %>
    <h2><%= f.label "Username" %></h2>
    <%= f.text_field(:username, :required => true) %>
    <h2><%= f.label "E-Mail" %></h2>
    <%= f.text_field :email, :required => true, :pattern => '^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$' %>
    <h2><%= f.label "Password" %></h2>
    <%= f.password_field(:password, :required => true) %>
    <h2><%= f.label "Confirm Password" %></h2>
    <%= f.password_field(:password_confirmation, :required => true) %>
    <h2>Zip Code </h2>
    <p>(we use this to help you find friends nearby!)</p>
    <%= text_field_tag :zip, nil, :required => true, :pattern => '^\d{5}$', :title => "Enter your 5 digit zip code" %>
    <br><%= f.submit "Sign Up", class: "submit" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="profile_pic">
  <%= render partial: "photos/show", locals: { user: @user } %>
</div>
<div class="info">
  <h3><%= @user.username.titlecase %>'s Book Buddies!</h3>
  <h4><%= !@user.location.nil? ? "#{@user.location.city}, #{@user.location.state}" : "No location set." %></h4>
  <%= link_to "Edit My Profile", edit_user_path(current_user) if @user == current_user %>
</div>

<section class="friends_list">
  <div class="body">
    <ul>
      <% current_user.book_friends.each do |friend|  %>
        <li class="friend_links">
          <div>
            <p><%=friend.username.titlecase%></p>
          </div>
          <div class="friend_img">
            <%= link_to render( partial: "photos/show", locals: { user: friend }), user_favorite_books_path(friend) %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</section>