config/routes.rb
Bookmeetups::Application.routes.draw do
  root to: 'users#landing'

  post "/search", to: "searches#search"
  get "users/landing", to: "users#landing"
  resources :users, :except => [:index] do
    post 'books/:book_id', to: 'favorite_books#create', as: 'create_favorite_book'
    delete 'books/:book_id', to: 'favorite_books#destroy', as: 'favorite_book'
    get 'books', to: 'favorite_books#index', as: 'favorite_books'
    get 'books/:book_id/new_meetup', to: 'meetups#create', as: 'create_meetup'
    resources :meetups, :except => [:new, :edit, :create, :destroy]
    resources :photos, :only => [:show, :new, :create, :destroy] do
      get "serve", :on => :member
    end
  end

  resources :books, only: [:show, :index]
  resources :sessions, :only => [:new, :create, :destroy]

  resources :meetups, :only => [] do
    resources :messages, only: [:new, :create]
  end


  get "/search/:s", to: "searches#results"
  get "/search", to: "searches#results"
end

app/views/shared/_nav.html.erb
<nav>
  <ul class="nav-horizontal">
    <% if logged_in? %>
      <li><%= link_to "Log Out", { :controller => :sessions, :action => :destroy, :id => session[:id] }, :method => :delete %></li>
      <li><%= link_to "My Books", user_favorite_books_path(current_user) %></li>
      <li><%= link_to "My Meetups", user_meetups_path(current_user) %></li>
      <li><%= link_to second_button_text, user_path(session[:id]) %></li>
      <% if current_user.unread > 0 %>
        <li class="incoming"><span><%= current_user.unread %></span></li>
      <% end %>
    <% else %>
      <li><%= link_to first_button_text, new_session_path %></li>
      <li><%= link_to second_button_text, new_user_path %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_unauthorized.html.erb
Mmmm sorry, no can do.

app/views/shared/unauthorized.html.erb
Mmmm sorry, no can do.