config/routes.rb
Bookmeetups::Application.routes.draw do
  root to: 'users#landing'

  post "/search", to: "searches#search"
  get "users/landing", to: "users#landing"
  resources :users, :except => [:index] do
    post 'books/:book_id', to: 'favorite_books#create', as: 'create_favorite_book'
    delete 'books/:book_id', to: 'favorite_books#destroy', as: 'favorite_book'
    get 'books', to: 'favorite_books#index', as: 'favorite_books'
    get 'books/:book_id/new_meetup', to: 'meetups#create', as: 'create_meetup'
    resources :meetups, :except => [:new, :edit, :create, :destroy]
    resources :photos, :only => [:show, :new, :create, :destroy] do
      get "serve", :on => :member
    end
  end

  resources :books, only: [:show, :index]
  resources :sessions, :only => [:new, :create, :destroy]

  resources :meetups, :only => [] do
    resources :messages, only: [:new, :create]
  end


  get "/search/:s", to: "searches#results"
  get "/search", to: "searches#results"
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :title, :author, :isbn
  validates_uniqueness_of :isbn, :google_id
  validates_uniqueness_of :author, :scope => :title

  validates :isbn, format: { with: /^\d{13}$/ }

  has_many :favorite_books
  has_many :users, through: :favorite_books
  has_many :meetups

  def photo_link( zoom = 2)
    "http://bks7.books.google.com/books?id=#{google_id}&printsec=frontcover&img=1&zoom=#{zoom}"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :redirect_unless_logged_in

  def index
    @books = Book.all
    render "index", layout: true
  end

  def show
    @book = Book.find(params[:id])
    @book_in_current_user_collection = current_user.books.include? @book
    @nearby_friends = current_user.friends(@book)
    @distant_friends = @book.users - [current_user] - @nearby_friends
    render "show", layout: true
  end
end

app/views/books/index.html.erb
<p>Book collection: </p>

<div class="book_list">
  <% @books.each do |book| %>
    <div class="book-display">
      <h4><%= book.title %></h4>
      <%= link_to image_tag(book.photo_link(1)), book_path(book), :class => "book-img"  %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="book_pic">
  <img src="<%= @book.photo_link(1) %>" alt="<%= @book.title %>">
</div>
<div class="info">

  <h4>Title: <%= @book.title %></h4>
  <h4>Author: <%= @book.author %></h4>
  <% if @book_in_current_user_collection %>
    <%= button_to "Remove from my collection", user_favorite_book_path(current_user.id, @book.id), :method => :delete, :class => "book-selector" %>
  <% else %>
    <%= button_to "Add to my collection", user_create_favorite_book_path(current_user.id, @book.id), :class => "book-selector" %>
  <% end %>
</div>

<section class="friends_list">
  <div class="body">
    <ul>
      <p>Your close friends for this book:</p>
      <% @nearby_friends.each do |friend| %>
        <li class="friend_links">
          <div>
            <p><%=friend.username.titlecase%></p>
          </div>
          <div class="friend_img">
            <%= link_to render( partial: "photos/show", locals: { user: friend }), user_favorite_books_path(friend) %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</section>

<section class="friends_list">
  <div class="body">
    <ul>
      <p>Your distant friends for this book:</p>
      <% @distant_friends.each do |friend| %>
        <li class="friend_links">
          <div>
            <p><%=friend.username.titlecase%></p>
          </div>
          <div class="friend_img">
            <%= link_to render( partial: "photos/show", locals: { user: friend }), user_favorite_books_path(friend) %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</section>